[package]
name = "RustleWeb"
version = "0.1.0"
edition = "2021"



[package.metadata]
authors=["Mohammad Hasani"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
